### ISSUE TITLE
Maintainers

### ISSUE THREAD

**Issue by monamok** [camaraproject/HomeDevicesQoD#3] opened 2022-11-04 09:19 UTC
Is anyone interested in joining the maintainers group? In case you are, please comment here.

Current Maintainers: 
https://github.com/camaraproject/HomeDevicesQoD/blob/main/MAINTAINERS.MD

**Comment by jpengar** [comment] 2022-12-05 11:55
Waiting DT technical contacts to be added as Maintainers before closing this issue.

**Comment by jpengar** [comment] 2023-01-19 15:05
To be CLOSED as soon DT contact/s are 100% confirmed. We are working with Noel Wirzius to get technical contact/s from DT and to get them involved in github project and API design. So far Rafal Artych (representing DT) is joining weekly calls. He already have access to github repository and is subscribed to the mailing list.

**Comment by jpengar** [comment] 2023-03-09 14:48
I will add @rartych as a maintainer, since he is the contact person from DT who is actively involved in the project. And I'm closing this topic, as there's no point in discussing it any further.

**Closed by jpengar** 2023-03-09 14:48 UTC
